# Generated by Django 4.1.13 on 2025-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(max_length=97)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DELETED')], default='A', max_length=1)),
                ('name', models.CharField(default=None, max_length=7, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'phone', 'email'], name='users_id_6abc5e_idx'),
        ),
    ]
