# Generated by Django 4.1.13 on 2025-06-07 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('referal_code', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DELETED')], max_length=1)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'referal_codes',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
