# Generated by Django 4.1.13 on 2025-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0004_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
