# Generated by Django 4.1.13 on 2025-10-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0005_user_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_path',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.BooleanField(default=False),
        ),
    ]
