# Generated by Django 4.1.13 on 2025-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('value', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('R', 'REDEEMED'), ('E', 'EXPIRED')], default='A', max_length=1)),
                ('userid_redeem', models.BigIntegerField(default=None, null=True)),
                ('date_redeem', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'referals',
            },
        ),
        migrations.AddIndex(
            model_name='referal',
            index=models.Index(fields=['user_id'], name='referals_user_id_6c9bb4_idx'),
        ),
    ]
