# Generated by Django 4.1.13 on 2025-10-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0006_remove_user_img_path_user_img'),
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='userid_redeem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginregister.user'),
        ),
    ]
