# Generated by Django 4.1.13 on 2025-10-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0002_alter_referal_userid_redeem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal',
            name='status',
        ),
    ]
