# Generated by Django 4.1.13 on 2025-10-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0003_remove_referal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal',
            name='date_redeem',
        ),
    ]
