# Generated by Django 4.1.13 on 2025-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0004_remove_referal_date_redeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='date_redeem',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
